name: Webapp CD

on:
  release:
    types: [published]
    tags: ["v*.*.*"]

env:
  FALCON_CLIENT_ID: "${{ secrets.FALCON_CLIENT_ID }}"
  FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
  FALCON_CLOUD_REGION: "${{ secrets.FALCON_CLOUD_REGION }}"

jobs:
  webapp-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Release Tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Get Image Prevention Policy Results
      run: |
        chmod +x scripts/image_prevention_policy_check.sh
        bash scripts/image_prevention_policy_check.sh
      env:
        IMAGE_REPO: "public/webapp-cicd-demo"
        IMAGE_TAG: "${{ steps.tag.outputs.tag }}"
    
    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    #- name: Azure Login
    #  uses: Azure/login@v1
    #  with:
    #    creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    #- name: Set AKS Context
    #  uses: azure/aks-set-context@v3
    #  with:
    #    resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
    #    cluster-name: ${{ env.AZURE_AKS_CLUSTERNAME }}

    #- name: Setup kubectl
    #  id: install-kubectl
    #  uses: azure/setup-kubectl@v3

    #- name: Deploy webapp to AKS
    #  uses: Azure/k8s-deploy@v4
    #  with:
    #    namespace: "default"
    #    manifests: |
    #        manifests/webapp.yaml
    #    images: "${{ env.CONTAINER_REPOSITORY }}:${{ steps.tag.outputs.tag }}"

